### Other
# 职业：术士
# 模式：标准模式
# 多头蛇年
#
# 2x (1) 慌乱的图书管理员 REV_242
# 2x (1) 烈焰小鬼 CORE_EX1_319
# 2x (1) 牺牲魔典
# 2x (1) 虚空行者 CORE_CS2_065 
# 2x (1) 邪恶船运 DED_504
# 2x (2) 灾祸降临
# 2x (2) 血缚小鬼 SW_084 
# 2x (2) 邪恶图书馆 REV_371
# 2x (3) 小鬼首领
# 2x (3) 恶魔法阵 CORE_GIL_191 
# 2x (3) 掩息海星
# 1x (4) 剑圣萨穆罗
# 2x (4) 调皮的小鬼 REV_244
# 2x (5) 阴暗的酒保
# 1x (6) 小鬼大王拉法姆 REV_835 
# 1x (6) 恐惧巫妖塔姆辛
# 1x (10) 海巨人
# 
AAECAcn1AgT76AOwkQSi1ASb5AQN1+0D/foD//oDxYAEhKAE5qAEjbUE+dME+tME/9kEgNoEgdoEq+oEAA==
# 
# 想要使用这副套牌，请先复制到剪贴板，然后在游戏中点击“新套牌”进行粘贴。
### 小鬼术
# Class: Warlock
# Format: Standard
# Year of the Hydra
#
# 2x (1) Flame Imp
# 2x (1) Flustered Librarian
# 1x (1) Grimoire of Sacrifice
# 2x (1) Voidwalker
# 2x (1) Wicked Shipment
# 2x (2) Bloodbound Imp
# 2x (2) Impending Catastrophe
# 2x (2) Vile Library
# 2x (3) Fiendish Circle
# 2x (3) Imp Gang Boss
# 1x (3) Smothering Starfish
# 2x (4) Mischievous Imp
# 2x (4) Murlocula
# 2x (5) Shady Bartender
# 1x (6) Dreadlich Tamsin
# 1x (6) Imp King Rafaam
# 2x (10) Sea Giant
#
AAECAf0GBNftA7CRBI21BJvkBA39+gP/+gPFgASEoATmoAT50wT60wSi1AT/2QSA2gSB2gTL4gSr6gQA
#
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
# Generated by HDT - https://hsreplay.net

AAECAf0GAo21BJvkBA7X7QP9+gP/+gOB+wPFgASEoATmoAT50wT60wSi1AT/2QSA2gSB2gSr6gQA
### 小鬼术
# 职业：术士
# 模式：标准模式
# 多头蛇年
#
# 2x (1) 慌乱的图书管理员
# 2x (1) 烈焰小鬼
# 2x (1) 虚空行者
# 2x (1) 邪恶船运
# 1x (2) 小鬼集群（等级1）
# 2x (2) 灾祸降临
# 2x (2) 邪恶图书馆
# 2x (3) 小鬼首领
# 1x (3) 布莱恩·铜须
# 2x (3) 恶魔法阵
# 1x (3) 掩息海星
# 2x (4) 调皮的小鬼
# 2x (4) 鱼人吸血鬼
# 2x (5) 阴暗的酒保
# 1x (6) 小鬼大王拉法姆
# 1x (6) 恐惧巫妖塔姆辛
# 1x (6) 逐罪者凯尔萨斯
# 1x (8) 老巨鳍
# 1x (10) 德纳修斯大帝
# 
AAECAcn1Agj07QOwkQSNtQT1xwTp0ASY1ASb5AS+8AQL//oDxYAEhKAE5qAE+dME+tME/9kEgNoEgdoEy+IEq+oEAA==
# 
# 想要使用这副套牌，请先复制到剪贴板，然后在游戏中点击“新套牌”进行粘贴。